"""
PS121 Handwritten Notes OCR — Mock OCR Provider (Development / Testing / Demo)
Provides deterministic, realistic handwritten note transcripts for offline demos and CI test suites.
Never used in production when OCR_PROVIDER=mistral.
"""

import time
import asyncio
import hashlib
from typing import Optional, Dict, Any, List

from ertmac.ocr.provider import OCRProvider
from ertmac.ocr.result import OCRInput, OCRResult, OCRBlock, OCRLine, OCRWord, ConfidenceLevel


DEMO_TRANSCRIPTS = [
    (
        "DRILLING LOG — SHIFT HANDOVER NOTE\n"
        "Date: 12/08/2026 | Time: 14:30 HRS | Rig: Slot #4\n"
        "Wellbore: 15/9-F-14 | Supervisor: E. Hansen\n\n"
        "OBSERVATIONS:\n"
        "- Mud temperature rose from 68°C to 84°C at 3,142m MD\n"
        "- Standpipe Pressure (SPP) steady at 185 bar with 2,400 L/min flow rate\n"
        "- Rotary RPM held at 120 RPM, torque fluctuating between 14-18 kNm\n"
        "- Mud density checked at shaker: 1.42 SG (active pit level: 48 m3)\n\n"
        "ACTIONS TAKEN & RECOMMENDATIONS:\n"
        "1. Replaced valve seal on HP mud pump #2\n"
        "2. Monitored background gas: peak 3.2% units at 3,150m MD\n"
        "3. Next shift: Perform flow check before tripping out drill string at 3,200m."
    ),
    (
        "EQUIPMENT INSPECTION & MAINTENANCE NOTE\n"
        "Asset ID: PUMP-MOD-8812 | Serial: SN-90231-X\n"
        "Date: 15/08/2026 | Inspector: D. Kumar\n\n"
        "1. Pump vibration recorded at 7.2 mm/s (threshold: 6.5 mm/s) — HIGH VIBRATION\n"
        "2. Minor lube oil leakage around drive shaft housing flange\n"
        "3. Suction pressure: 4.8 bar | Discharge pressure: 162 bar\n\n"
        "MAINTENANCE REQUIRED:\n"
        "- Replace drive shaft mechanical seal and inspect roller bearings\n"
        "- Retorque flange bolts to 320 Nm before restart\n"
        "- Follow up tomorrow at morning handover."
    ),
    (
        "GEOLOGICAL CORE SAMPLE OBSERVATION\n"
        "Interval: 2,840.0m - 2,849.5m MD | Formation: Hugin Sandstone\n"
        "Logged by: Sarah Jenkins | Date: 18/08/2026\n\n"
        "Lithology: Fine to medium grained quartz sandstone, moderately sorted.\n"
        "Porosity estimated: 18-22% with faint yellowish hydrocarbon fluorescence.\n"
        "Core recovery: 9.3m (97.8% recovery rate).\n"
        "Action: Send sample plugs to reservoir lab for permeability analysis."
    )
]


class MockOCRProvider(OCRProvider):
    """
    Mock OCR Provider for development and offline testing.
    Produces realistic handwritten drill notes with deterministic selection based on image hash.
    """

    def __init__(self, simulated_delay_ms: int = 400, default_model: str = "mock-handwriting-v1"):
        self._simulated_delay_ms = simulated_delay_ms
        self._default_model = default_model

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def default_model(self) -> str:
        return self._default_model

    async def health_check(self) -> bool:
        return True

    async def extract_text(self, ocr_input: OCRInput, model: Optional[str] = None) -> OCRResult:
        start_time = time.time()
        
        # Simulate processing delay
        if self._simulated_delay_ms > 0:
            await asyncio.sleep(self._simulated_delay_ms / 1000.0)

        # Pick transcript deterministically from image bytes checksum
        h = int(hashlib.md5(ocr_input.image_bytes).hexdigest(), 16)
        transcript = DEMO_TRANSCRIPTS[h % len(DEMO_TRANSCRIPTS)]
        
        duration_ms = int((time.time() - start_time) * 1000)

        paragraphs = [p.strip() for p in transcript.split("\n\n") if p.strip()]
        blocks = [
            OCRBlock(
                block_type="paragraph",
                text=p,
                confidence=0.94,
            )
            for p in paragraphs
        ]

        return OCRResult(
            provider="mock",
            model=model or self._default_model,
            raw_text=transcript,
            normalized_text=transcript.strip(),
            confidence=0.94,
            confidence_level=ConfidenceLevel.HIGH,
            processing_time_ms=duration_ms,
            blocks=blocks,
            raw_response={"mock": True, "checksum": hashlib.sha256(ocr_input.image_bytes).hexdigest()},
            metadata={
                "mock_mode": True,
                "warning": "Generated by MockOCRProvider (Development/Demo mode)",
                "source_filename": ocr_input.filename,
            },
        )
